spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    # Compatibility Mode For PostgresSQL and Do NOT Close a Database when the VM Exits
    #url: jdbc:h2:mem:TEST;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:~/dataset/hero-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:/dataset/schema-h2.sql
logging:
  level:
    root: INFO
    org.springframework: ERROR
